[package]
name = "iris"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-tpu-client-next = { git = "https://github.com/anza-xyz/agave.git", default-features = false }
solana-client = { git = "https://github.com/anza-xyz/agave.git" }
solana-transaction-status = { git = "https://github.com/anza-xyz/agave.git", default-features = false }
solana-sdk = { git = "https://github.com/anza-xyz/agave.git", default-features = false }
solana-rpc-client-api ={ git = "https://github.com/anza-xyz/agave.git" }
solana-connection-cache = { git = "https://github.com/anza-xyz/agave.git", default-features = false }

jsonrpsee = {version = "=0.24.5", features = ["server", "http-client", "macros"]}
tokio = "1.40.0"
env_logger = "0.11.5"
tokio-util = "0.7.12"
dashmap = "5.5.3"
bincode = "1.3.3"
figment = {version = "0.10.19", features = ["env"]}
serde = { version = "1.0.188", features = ["derive"] }
anyhow = "1.0.91"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
dotenv = "0.15.0"
base64 = "0.22.1"
log = "0.4.22"
metrics = "0.24.0"
metrics-exporter-prometheus = "0.16.0"
futures-util = "0.3.31"
rustls = { version = "0.23.17", features = ["ring"]  }

[patch.crates-io]
solana-program = { git = "https://github.com/anza-xyz/agave.git" }
solana-curve25519 = { git = "https://github.com/anza-xyz/agave.git" }
solana-zk-sdk = { git = "https://github.com/anza-xyz/agave.git" }
solana-zk-token-sdk = { git = "https://github.com/anza-xyz/agave.git" }

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
