[workspace]
members = ["iris-rpc"]
resolver = "2"

[workspace.package]
version = "0.0.1"

[workspace.dependencies]
solana-tpu-client-next = { version = "~2.1.1", default-features = false }
solana-client = { version = "~2.1.1" }
solana-transaction-status = { version = "~2.1.1", default-features = false }
solana-sdk = { version = "~2.1.1", default-features = false }
solana-rpc-client-api = { version = "~2.1.1" }
solana-connection-cache = { version = "~2.1.1", default-features = false }

yellowstone-grpc-client = { git = "https://github.com/rpcpool/yellowstone-grpc.git", tag = "v4.0.0+solana.2.1.1" }
yellowstone-grpc-proto = { git = "https://github.com/rpcpool/yellowstone-grpc.git", tag = "v4.0.0+solana.2.1.1", default-features = false }

jsonrpsee = { version = "=0.24.5", features = ["server", "http-client", "macros"] }
tokio = "1.40.0"
env_logger = "0.11.5"
tokio-util = "0.7.12"
dashmap = "5.5.3"
bincode = "1.3.3"
figment = { version = "0.10.19", features = ["env"] }
serde = { version = "1.0.188", features = ["derive"] }
anyhow = "1.0.91"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
dotenv = "0.15.0"
base64 = "0.22.1"
log = "0.4.22"
metrics = "0.24.0"
metrics-exporter-prometheus = "0.16.0"
futures-util = "0.3.31"
rustls = { version = "0.23.17", features = ["ring"] }
rand = "0.8.5"